### ISSUE TITLE
Getting students to do it themselves

### ISSUE THREAD

**Issue by jssimpson20** [Bucknell-Biol364/Rtutorial#5]
https://github.com/Bucknell-Biol364/Rtutorial/blob/eb213fc00fd06acad21366dfdbf0aa837851f013/Rtutorial_anbe.R#L46

I like that the students have to look through the data and decide which variable they want to test the mean of, but maybe specify that they will have to choose a variable from that dataset, and then replace "Variable" with the actual name of the column they want. (instead of just running that line of code, which would throw an error)

**Comment by jfberhane** [comment]
@jssimpson20 Thanks for the suggestion! I added more clarifications about my use of generic names in the code so that students know to alter them.
