### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jssimpson20** [Bucknell-Biol364/Rtutorial#6]
https://github.com/Bucknell-Biol364/Rtutorial/blob/eb213fc00fd06acad21366dfdbf0aa837851f013/Rtutorial_anbe.R#L100

When running this line of code --> simple.eda(ResearchObs)

I received this error:

> simple.eda(ResearchObs)
Error in is.finite(x) : default method not implemented for type 'list'

**Comment by jfberhane** [comment]
@jssimpson20 yea simple.eda is gross when you use it on the full data set because there are a lot of variables of all different types. I changed the tutorial to just explain simple.eda in the data exploration section but to not be used until a little later

Thanks!
